package f.star.iota.milk;

public interface Menus {
    String MENU_SETTINGS = "设置";
    int MENU_SETTINGS_ID = 999;
    String MENU_ABOUT = "关于";
    int MENU_ABOUT_ID = 998;

    String MENU_ILLUSTRATION = "插画";
    int MENU_ILLUSTRATION_ID = 996;

    String MENU_MEIZI = "妹子";
    int MENU_MEIZI_ID = 995;

    String MENU_WALLPAPER = "壁纸";
    int MENU_WALLPAPER_ID = 994;

    String MENU_YANDE = "YANDE";
    int MENU_YANDE_ID = 1;

    String MENU_KONACHAN = "KONACHAN";
    int MENU_KONACHAN_ID = 2;

    String MENU_LOLIBOORU = "LOLIBOORU";
    int MENU_LOLIBOORU_ID = 3;

    String MENU_DANBOORU = "DANBOORU";
    int MENU_DANBOORU_ID = 4;

    String MENU_SAFEBOORU = "SAFEBOORU";
    int MENU_SAFEBOORU_ID = 5;

    String MENU_E621 = "E621";
    int MENU_E621_ID = 6;

    String MENU_E926 = "E926";
    int MENU_E926_ID = 7;

    String MENU_ANIME_PICTURES = "ANIME-PICTURES";
    int MENU_ANIME_PICTURES_ID = 8;

    String MENU_BEHOIMI = "BEHOIMI";
    int MENU_BEHOIMI_ID = 9;

    String MENU_WALLHAVEN = "WALLHAVEN";
    int MENU_WALLHAVEN_ID = 10;

    String MENU_GANK = "GANK";
    int MENU_GANK_ID = 11;

    String MENU_BING = "BING";
    int MENU_BING_ID = 12;

    String MENU_TNGOU = "TNGOU";
    int MENU_TNGOU_ID = 13;

    String MENU_GACHA = "GACHA";
    int MENU_GACHA_ID = 14;

    String MENU_BCY_SELECTED = "BCY SELECTED";
    int MENU_BCY_ILLUST_SELECTED_ID = 15;
    int MENU_BCY_COS_SELECTED_ID = 16;

    String MENU_BCY = "BCY";
    String MENU_BCY_RANKING = "BCY RANKING";
    int MENU_BCY_ILLUST_RANKING_ID = 17;
    int MENU_BCY_COS_RANKING_ID = 18;

    String MENU_MANGA_DRAWING = "MANGA DRAWING";
    int MENU_MANGA_DRAWING_ID = 19;
    String MENU_MANGA_DRAWING_HENTAI = "MANGA DRAWING HENTAI";
    int MENU_MANGA_DRAWING_HENTAI_ID = 20;

    String MENU_MAG_MOE = "MAG MOE";
    int MENU_MAG_MOE_MOE_ID = 21;
    int MENU_MAG_MOE_COS_STAR_ID = 22;

    String MENU_APIC = "APIC";
    int MENU_APIC_ID = 23;

    String MENU_ZEROCHAN = "ZEROCHAN";
    int MENU_ZEROCHAN_ID = 24;

    String MENU_E_SHUUSHUU = "E-SHUUSHUU";
    int MENU_E_SHUUSHUU_ID = 25;

    String MENU_MINITOKYO = "MINITOKYO";
    int MENU_MINITOKYO_ID = 26;

    String MENU_WWW_005_TV = "WWW.005.TV";
    int MENU_WWW_005_TV_ACG_ID = 27;
    int MENU_WWW_005_TV_COS_ID = 28;

    String MENU_JDLINGYU = "JDLINGYU";
    int MENU_JDLINGYU_ACG_ID = 30;
    int MENU_JDLINGYU_MEIZHI_ID = 31;

    String MENU_LESMAO = "LESMAO";
    int MENU_LESMAO_ID = 32;

    String MENU_XIUMM = "XIUMM";
    int MENU_XIUMM_ID = 33;

    String MENU_94TAOTU = "94TAOTU";
    int MENU_94TAOTU_ID = 34;

    String MENU_MZITU = "MZITU";
    int MENU_MZITU_ID = 35;

    String MENU_MMONLY = "MMONLY";
    int MENU_MMONLY_ID = 36;

    String MENU_ROSIYY = "ROSIYY";
    int MENU_ROSIYY_ID = 37;

    String MENU_192TT = "192TT";
    int MENU_192TT_ID = 38;

    String MENU_XIUREN = "XIUREN";
    int MENU_XIUREN_ID = 39;

    String MENU_LINGYU = "LINGYU";
    int MENU_LINGYU_ID = 40;

    String MENU_MOEIMG = "MOEIMG";
    int MENU_MOEIMG_ID = 41;

    String MENU_NIJIERO_CH = "NIJIERO-CH";
    int MENU_NIJIERO_CH_ID = 42;

    String MENU_COSPLAY_LA = "COSPLAY.LA";
    int MENU_COSPLAY_LA_ID = 43;

    String MENU_CHINAGIRLOL = "CHINAGIRLOL";
    int MENU_CHINAGIRLOL_ID = 44;

    String MENU_MOE005TV = "MOE.005.TV";
    int MENU_MOE005TV_ACG_ID = 45;
    int MENU_MOE005TV_COS_ID = 46;

    String MENU_ACG_GAMERSKY = "ACG.GAMERSKY";
    int MENU_ACG_GAMERSKY_ACG_ID = 47;
    int MENU_ACG_GAMERSKY_COS_ID = 48;

    String MENU_PANGCI = "PANGCI";
    int MENU_PANGCI_ID = 49;

    String MENU_YURIIMG = "YURIIMG";
    int MENU_YURIIMG_ID = 50;

    String MENU_MIAOWU = "MIAOWU";
    int MENU_MIAOWU_ID = 51;

    String MENU_MEIMEIZI = "MEIMEIZI";
    int MENU_MEIMEIZI_ID = 52;

    String MENU_YOUWU = "YOUWU";
    int MENU_YOUWU_ID = 53;

    String MENU_TAOTUTT = "TAOTUTT";
    int MENU_TAOTUTT_ID = 54;

    String MENU_UMEI = "UMEI";
    int MENU_UMEI_ID = 55;

    String MENU_GRAVUREGIRLZ = "GRAVUREGIRLZ";
    int MENU_GRAVUREGIRLZ_ID = 56;

    String MENU_SIMPLEDESKTOPS = "SIMPLEDESKTOPS";
    int MENU_SIMPLEDESKTOPS_ID = 57;

    String MENU_BILIBILI = "BILIBILI";
    int MENU_BILIBILI_ID = 58;

    String MENU_ARTSTATION = "ARTSTATION";
    int MENU_ARTSTATION_ID = 59;

    String MENU_KUVVA = "KUVVA";
    int MENU_KUVVA_ID = 60;

    String MENU_ISUJIN = "ISUJIN";
    int MENU_ISUJIN_ID = 61;

    String MENU_JUSTINMALLER = "JUSTINMALLER";
    int MENU_JUSTINMALLER_ID = 62;

    String MENU_GAMERSKY = "GAMERSKY";
    int MENU_GAMERSKY_ID = 63;

    String MENU_MAGDELEINE = "MAGDELEINE";
    int MENU_MAGDELEINE_ID = 64;

    String MENU_ALPHACODERS = "ALPHACODERS";
    int MENU_ALPHACODERS_ID = 65;

    String MENU_MMJPG = "MMJPG";
    int MENU_MMJPG_ID = 66;

    String MENU_GIRL_ATLAS = "GIRL-ATLAS";
    int MENU_GIRL_ATLAS_ID = 67;

    String MENU_ZDT8 = "ZDT8";
    int MENU_ZDT8_ID = 68;

    String MENU_A_KABE = "A-KABE";
    int MENU_A_KABE_ID = 69;
}
